name: C/C++ CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install tex tool
      run: |
        sudo apt update
        sudo apt upgrade --yes
        sudo apt install texlive --assume-yes --install-recommends 
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          SERBERT-*.tar.gz
          serbert
          
