name: C/C++ CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  push:
    branches: [ "release" ]
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install tex tool
      run: |
        sudo apt update
        sudo apt upgrade --yes
        sudo apt install texlive --assume-yes --install-recommends 
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}
        #repository: the-moog/serbert
        # note you'll typically need to create a personal access token
        # with permissions to create releases in the other repo
        # token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: |
          serbert-*.tar.gz
          serbert
          
